// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djccnysbqfgvmcdreizd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqY2NueXNicWZndm1jZHJlaXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTg5MjUsImV4cCI6MjA2ODE3NDkyNX0.XL0zAcJ-a5I4WckRHeZsU1_yNx1SqhNtALXHglJUB_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});